location_parameters:
  exp_folder: '/mnt/2e6952d2-a327-41fa-9451-7ce13129d27c/HTS0033/'
  experiment_name: 'HTN0001'
  saving_folder: '/home/biancamigliori/Documents/GBA/'
  Plates: ['101','102']
  plate_type: '_CV384W_'

type_specific:
  channel: ['ch4','ch1','ch2','ch3','ch5']          
  MaskCNN: True
  stack: False
  ROI: 299
  neural_tracing: 'ch2'

QC: True
use_cpu_segmentation: False
img_size: 2160
csv_coordinates: '' 

device: "0"
gpu_mrcnn: 0


AWS: 
  use_AWS: 'no'
  query_function: 'data_query.query_functions_AWS'

local:
  query_function: 'data_query.query_functions_local'