vector_type: 'scalefex' #'scalefex', 'embeddings'


location_parameters:
  exp_folder: '/mnt/Syn18/HTDEV0026 iPSC Cell Painting Test/Cell Painting/'
  experiment_name: 'HTDEV0026'
  saving_folder: '/home/biancamigliori/Documents/HCI_Projects/iPSC/'
  plates: ['101','102'] 
  plate_type: '_CCU384_'
  coordinates_csv: ''
  image_size: [2160,2160]

type_specific:
  channel: ['ch4','ch2', 'ch3',  'ch1']        
  stack: False
  ROI: 90
  neurite_tracing: ''
  RNA_channel: '' #set only if you want to compute ScaleFex
  Mito_channel: '' #set only if you want to compute ScaleFex
  zstack: True
  img_size: [2160,2160]
  compute_live_cells: False 


downsampling: 1
QC: True
FFC: True
FFC_location: 'Saving Folder'
FFC_n_images: 500
tile_computation: False

segmentation:
  csv_coordinates: '' 
  segmenting_function: 'Nuclei_segmentation.nuclei_location_extraction' # 'MaskRCNN_Deployment.segmentation_mrcnn'   
  MaskRCNN_cell_segmentation: False
  Threshold_segmentation: True
  use_cpu_segmentation: True
  min_cell_size: 200 #area
  max_cell_size: 1000
  visualization: True
  

## embeddings_settings
device: "1"
weights_location: "/home/biancamigliori/Documents/GitHubRepos/NYSCF_Embeddings_pipeline"

## Scalefex settings
visualize_masks: False
visualize_crops: True

gpu_mrcnn: 'cpu'


AWS: 
  use_AWS: 'no'
  query_function: 'data_query.query_functions_AWS'

local:
  query_function: 'data_query.query_functions_local'
  parallel: False
  n_of_workers: 100