vector_type: 'scalefex' #'scalefex'


location_parameters:
  exp_folder: '/mnt/2e6952d2-a327-41fa-9451-7ce13129d27c/HTS0033/'
  experiment_name: 'HTS0033'
  saving_folder: '/home/biancamigliori/Desktop/temp_try_output/'
  plates: ['101','102']
  plate_type: '_CV384W_'
  coordinates_csv: ''
  image_size: [2160,2160]

type_specific:
  channel: ['ch4','ch1','ch2','ch3','ch5']          
  MaskCNN: True
  stack: False
  ROI: 299
  neural_tracing: 'ch2'
  RNA_channel: 'ch5' #set only if you want to compute ScaleFex
  Mito_channel: 'ch2' #set only if you want to compute ScaleFex
  zstack: False
  img_size: [2160,2160]
  compute_live_cells: False 
  neurite_tracing: ''

downsampling: 1
QC: True
FFC: True
FFC_location: 'Saving Folder'
FFC_n_images: 30
tile_computation: False

segmentation:
  csv_coordinates: '' 
  segmenting_function: 'Nuclei_segmentation.nuclei_location_extraction'
  MaskRCNN_cell_segmentation: False
  Threshold_segmentation: True
  use_cpu_segmentation: False
  min_cell_size: 100 #area
  max_cell_size: 10000
  

## embeddings_settings
device: "0"
weights_location: "/home/biancamigliori/Documents/GitHubRepos/NYSCF_Embeddings_pipeline"
#

gpu_mrcnn: 0


AWS: 
  use_AWS: 'no'
  query_function: 'data_query.query_functions_AWS'

local:
  query_function: 'data_query.query_functions_local'
  parallel: False