vector_type: 'embeddings' #'scalefex', 'embeddings' '' for QC only, 'coordinates' for coordinates of cells
resource: 'local' #'local', 'AWS'
n_of_workers: 1

# location_parameters:
exp_folder: '/mnt/synology01/HTF0006/BF Scans/'
experiment_name: 'HTF0006'
saving_folder: '/mnt/external1/Addie_HCI_Projects/HTF0006/' #'/mnt/data-storage/HCI_Projects/Neurons/HTS0026/'
plates: 'HTF0006_CV384W_201__2024-04-22T23_12_23-Measurement 2'

plate_identifier: 'HTF0006_CV384W_201__2024-04-22T23_12_23-Measurement 2'
fname_pattern: 'Images/<Well(6)><Site(3)><Plane(3)>-<Channel(3)>.<ext>' # Phenix pattern
fname_delimiters: ['-','.']
file_extensions: ['tiff']
image_size: [1080, 1080]
zstack: False

# type_specific:
channel: ['ch2']        
ROI: 75
neurite_tracing: ''
bf_channel: 'ch2'
RNA_channel: '' #set only if you want to compute ScaleFex
Mito_channel: '' #set only if you want to compute ScaleFex
zstack: False
compute_live_cells: False 
max_file_size: 2000

downsampling: 1
QC: True
FFC: False
FFC_n_images: 500
tile_computation: False

## segmentation:
csv_coordinates: '' # '' if you don't want to use a pre-computed coordinates file
segmenting_function: 'MaskRCNN_Deployment.segmentation_mrcnn' # 'MaskRCNN_Deployment.segmentation_mrcnn'  #'Nuclei_segmentation.nuclei_location_extraction' #'Nuclei_segmentation.nuclei_location_extraction'    
AI_cell_segmentation: False
save_coordinates: True
gpu_AI: '0'
use_cpu_segmentation: True
min_cell_size: 200 #area
max_cell_size: 100000
visualization: False
segment_brighfield: True # set for segmenting bf images

## embeddings_settings
device: '0'
weights_location: "/home/intern/NYSCF_HCI_image_processing/Embeddings_extraction_from_image/"

## Scalefex settings
visualize_masks: False
visualize_crops: False

#AWS settings
s3_bucket: 'nyscf-scalefex'
subset: 'A'
