vector_type: 'embeddings' #'scalefex', 'embeddings'
resource: 'local' #'local', 'AWS'
n_of_workers: 1

# location_parameters:
exp_folder: '/mnt/2e6952d2-a327-41fa-9451-7ce13129d27c/HTS0033/'
experiment_name: 'HTS0033'
saving_folder: '/home/biancamigliori/Desktop/temp_try_output/' #'/mnt/data-storage/HCI_Projects/Neurons/HTS0026/'
plates: ['106'] # ['HTS0026_CV384W_101__2022-10-15T22_41_08-Measurement 5',

plate_type: '_CV384W_'
fname_pattern: 'Images/<Well(6)><Site(3)><Plane(3)>-<Channel(3)>.<ext>' # Phenix pattern
fname_delimiters: ['-','.']
file_extensions: ['tiff']
image_size: [2160,2160]

# type_specific:
channel: ['ch4','ch1', 'ch5',  'ch3', 'ch2']        
stack: False
ROI: 150
neurite_tracing: ''
RNA_channel: 'ch5' #set only if you want to compute ScaleFex
Mito_channel: 'ch2' #set only if you want to compute ScaleFex
zstack: False
compute_live_cells: False 

downsampling: 1
QC: False
FFC: True
FFC_n_images: 500
tile_computation: False

# segmentation:
csv_coordinates: '' # '' if you don't want to use a pre-computed coordinates file
segmenting_function: 'Nuclei_segmentation.nuclei_location_extraction' # 'MaskRCNN_Deployment.segmentation_mrcnn'   
MaskRCNN_cell_segmentation: False
gpu_mrcnn: 0
Threshold_segmentation: True
use_cpu_segmentation: False
min_cell_size: 200 #area
max_cell_size: 100000
visualization: False

## embeddings_settings
device: "1"
weights_location: "/home/biancamigliori/Documents/models/"

## Scalefex settings
visualize_masks: False
visualize_crops: False

#AWS settings
s3_bucket: 'nyscf-scalefex'
subset: 'A'
