vector_type: 'scalefex' #'scalefex', 'embeddings'


location_parameters:
  exp_folder: '/mnt/synology01/HTN0001/'
  experiment_name: 'HTN0001'
  saving_folder: '/mnt/data-storage/HCI_Projects/Neurons/HTN0001'
  plates: ['HTN0001_CCU384_401__2024-02-17T22_04_34-Measurement 19',
            'HTN0001_CCU384_402__2024-02-13T22_52_28-Measurement 19',
            'HTN0001_CCU384_403__2024-02-14T23_02_44-Measurement 19',
            'HTN0001_CCU384_404__2024-02-15T23_28_53-Measurement 19'] 
  plate_type: '_CCU384_'
  fname_pattern: 'Images/<Well(6)><Site(3)><Plane(3)>-<Channel(3)>.<ext>' # Phenix pattern
  fname_delimiters: ['-','.']
  file_extensions: ['tiff']
  coordinates_csv: ''
  image_size: [2160,2160]

type_specific:
  channel: ['ch1','ch2', 'ch3',  'ch4']        
  MaskCNN: True
  stack: False
  ROI: 90
  neurite_tracing: ''
  RNA_channel: '' #set only if you want to compute ScaleFex
  Mito_channel: '' #set only if you want to compute ScaleFex
  zstack: True
  img_size: [2160,2160]
  compute_live_cells: False 


downsampling: 1
QC: False
FFC: False
FFC_location: 'Saving Folder'
FFC_n_images: 500
tile_computation: False

segmentation:
  csv_coordinates: '' 
  segmenting_function: 'Nuclei_segmentation.nuclei_location_extraction'
  MaskRCNN_cell_segmentation: False
  Threshold_segmentation: True
  use_cpu_segmentation: False
  min_cell_size: 100 #area
  max_cell_size: 5000
  visualization: False
  

## embeddings_settings
device: "0"
weights_location: "/home/biancamigliori/Documents/GitHubRepos/NYSCF_Embeddings_pipeline"

## Scalefex settings
visualize_masks: False

gpu_mrcnn: 0


AWS: 
  use_AWS: 'no'
  query_function: 'data_query.query_functions_AWS'

local:
  query_function: 'data_query.query_functions_local'
  parallel: True
  n_of_workers: 100