name: macos-latest
on: 
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "main" ]

jobs:
    macos-latest-build:
        uses: ./.github/workflows/python-package.yml
        with:
            os: macos-13