name: ubuntu-latest
on: 
    pull_request:
        branches: [ "main" ]
    push:
        branches: [ "main" ]

jobs:
    ubuntu-latest-build:
        uses: ./.github/workflows/python-package.yml
        with:
            os: ubuntu-latest